name: NXBoost Coin
version: 0.10.2-1
summary: "NXBoost: Blockchain driven VPN https://nxboost.com"
description: |
    NXBoost is a private, secure, untraceable, decentralised digital currency.
    It is the fuel for the distributed NXBoost Virtual Private Network (VPN).
grade: devel
confinement: strict

apps:
    nxboostd:
        daemon: forking
        command: |
          nxboostd-wrapper --detach --data-dir ${SNAP_COMMON} --config-file ${SNAP_USER_DATA}/etc/nxboostd.conf
        plugs:
            - network
            - network-bind
    nxboost-wallet-rpc:
        command: |
          nxboost-wallet-rpc --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network
            - network-bind
    nxboost-wallet-cli:
        command: |
          nxboost-wallet-cli --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network

parts:
    cmake-build:
        plugin: cmake
        configflags:
            - -DBDB_STATIC=1
            - -DUPNP_STATIC=1
            - -DBoost_USE_STATIC_LIBS=1
            - -DBoost_USE_STATIC_RUNTIME=1
            - -DARCH=default
        source: .
        build-packages:
            - gcc
            - pkg-config
            - libunbound-dev
            - libevent-dev
            - libboost-all-dev
            - libdb-dev
            - libunwind-dev
            - libminiupnpc-dev
            - libldns-dev
            - libexpat1-dev
            - bison
            - doxygen
            - graphviz
        stage-packages:
            - libminiupnpc10
            - libunbound2
            - libunwind8
        prime:
            - bin
            - usr/lib/
            - -usr/lib/gcc
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        organize:
            contrib/snap/nxboostd.conf: etc/nxboostd.conf
            contrib/snap/nxboostd-wrapper: bin/nxboostd-wrapper
        prime:
            - etc
            - bin
